from canvasapi import Canvas
from datetime import datetime
import html
from html.parser import HTMLParser
import re

STUDY_BLOCK_TITLE_PREFIX = "study block for "
STUDY_BLOCK_DESCRIPTION_MARKER = "Generated by Smart Canvas Planner"


class _CanvasHTMLTextExtractor(HTMLParser):
    BLOCK_TAGS = {"br", "div", "p", "li", "tr", "h1", "h2", "h3", "h4", "h5", "h6"}

    def __init__(self):
        super().__init__()
        self.parts = []

    def handle_starttag(self, tag, attrs):
        if tag in self.BLOCK_TAGS:
            self.parts.append("\n")

    def handle_endtag(self, tag):
        if tag in self.BLOCK_TAGS:
            self.parts.append("\n")

    def handle_data(self, data):
        self.parts.append(data)

    def text(self):
        return "".join(self.parts)


class CanvasInterface:
    def __init__(self, token, base_url):
        self.canvas = Canvas(base_url, token)
        self.user = self.canvas.get_current_user()
        self._assignment_group_cache = {}
        self._full_assignment_cache = {}

    @staticmethod
    def _get_value(obj, key, default=None):
        if isinstance(obj, dict):
            return obj.get(key, default)
        return getattr(obj, key, default)

    @staticmethod
    def _course_id_from_context(context_code):
        if not context_code or not str(context_code).startswith("course_"):
            return None

        try:
            return int(str(context_code).replace("course_", "", 1))
        except ValueError:
            return None

    @staticmethod
    def _normalize_weight(weight, default=1.0):
        if weight in (None, ""):
            return default

        text = str(weight).strip()
        if text.endswith("%"):
            text = text[:-1]

        try:
            number = float(text)
        except (TypeError, ValueError):
            return default

        if number > 1:
            return number / 100
        return number

    @staticmethod
    def _weight_percent(weight):
        try:
            return round(float(weight) * 100, 2)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _calendar_boundary(value, end_of_day=False):
        if isinstance(value, datetime):
            return value.isoformat()

        text = str(value).strip()
        if "T" in text:
            return text

        suffix = "T23:59:59Z" if end_of_day else "T00:00:00Z"
        return f"{text}{suffix}"

    @staticmethod
    def _is_generated_study_block(event):
        title = str(getattr(event, "title", "") or "").strip().lower()
        description = str(getattr(event, "description", "") or "")

        return (
            title.startswith(STUDY_BLOCK_TITLE_PREFIX)
            or STUDY_BLOCK_DESCRIPTION_MARKER in description
        )

    @staticmethod
    def _html_to_text(value):
        if value in (None, ""):
            return ""

        parser = _CanvasHTMLTextExtractor()
        try:
            parser.feed(str(value))
            raw_text = parser.text()
        except Exception:
            raw_text = str(value)

        raw_text = html.unescape(raw_text)
        lines = [
            re.sub(r"[ \t]+", " ", line).strip()
            for line in raw_text.splitlines()
        ]
        return "\n".join(line for line in lines if line)

    def _get_assignment_group_lookup(self, course_id):
        if course_id is None:
            return {}

        if course_id in self._assignment_group_cache:
            return self._assignment_group_cache[course_id]

        try:
            course = self.canvas.get_course(course_id)
            weighted = getattr(course, "apply_assignment_group_weights", False)
            groups = course.get_assignment_groups()
        except Exception:
            self._assignment_group_cache[course_id] = {}
            return {}

        lookup = {}
        for group in groups:
            group_id = self._get_value(group, "id")
            raw_weight = self._get_value(group, "group_weight", 0)
            weight = self._normalize_weight(raw_weight, default=0 if weighted else 1)
            group_info = {
                "name": self._get_value(group, "name", "Unknown category"),
                "weight": weight,
                "weight_percent": self._weight_percent(weight),
                "weighted_grading": weighted,
            }
            lookup[group_id] = group_info
            lookup[str(group_id)] = group_info

        self._assignment_group_cache[course_id] = lookup
        return lookup

    def _get_full_assignment(self, course_id, assignment_id):
        if course_id is None or assignment_id is None:
            return None

        cache_key = (course_id, assignment_id)
        if cache_key in self._full_assignment_cache:
            return self._full_assignment_cache[cache_key]

        try:
            course = self.canvas.get_course(course_id)
            assignment = course.get_assignment(assignment_id)
        except Exception:
            assignment = None

        self._full_assignment_cache[cache_key] = assignment
        return assignment

    def _assignment_value(self, calendar_assignment, full_assignment, key, default=None):
        value = self._get_value(calendar_assignment, key)
        if value is not None:
            return value
        return self._get_value(full_assignment, key, default)

    def _assignment_payload(self, calendar_event, context_code):
        assignment = self._get_value(calendar_event, "assignment")
        course_id = (
            self._course_id_from_context(context_code)
            or self._get_value(assignment, "course_id")
        )
        assignment_id = (
            self._get_value(assignment, "id")
            or self._get_value(calendar_event, "assignment_id")
        )

        full_assignment = self._get_full_assignment(course_id, assignment_id)
        assignment_group_id = self._assignment_value(assignment, full_assignment, "assignment_group_id")
        points = self._assignment_value(assignment, full_assignment, "points_possible")
        due_at = (
            self._get_value(calendar_event, "start_at")
            or self._assignment_value(assignment, full_assignment, "due_at")
        )
        description_html = (
            self._assignment_value(assignment, full_assignment, "description")
            or self._get_value(calendar_event, "description")
        )

        group_lookup = self._get_assignment_group_lookup(course_id)
        group_info = (
            group_lookup.get(assignment_group_id)
            or group_lookup.get(str(assignment_group_id))
            or {}
        )
        group_weight = group_info.get("weight", 1.0)

        title = (
            self._get_value(calendar_event, "title")
            or self._get_value(assignment, "name")
            or self._get_value(full_assignment, "name")
            or "Untitled"
        )
        context_name = self._get_value(calendar_event, "context_name", "Unknown")
        event_id = self._get_value(calendar_event, "id")
        item_id = assignment_id or event_id or f"{context_code}:{title}:{due_at}"
        instructions = self._html_to_text(description_html)

        return {
            "id": f"assignment_{course_id or context_code}_{item_id}",
            "include": True,
            "canvas_assignment_id": assignment_id,
            "canvas_event_id": event_id,
            "context_code": context_code,
            "course_id": course_id,
            "course_name": context_name,
            "context": context_name,
            "title": title,
            "due_at": due_at,
            "points": points or 0,
            "assignment_group_id": assignment_group_id,
            "assignment_group_name": group_info.get("name", "Unweighted"),
            "group_weight": group_weight,
            "group_weight_percent": group_info.get("weight_percent", self._weight_percent(group_weight)),
            "description": instructions,
            "instructions": instructions,
            "description_html": description_html or "",
            "submission_types": self._assignment_value(assignment, full_assignment, "submission_types", []),
            "allowed_extensions": self._assignment_value(assignment, full_assignment, "allowed_extensions", []),
            "grading_type": self._assignment_value(assignment, full_assignment, "grading_type"),
            "allowed_attempts": self._assignment_value(assignment, full_assignment, "allowed_attempts"),
            "lock_at": self._assignment_value(assignment, full_assignment, "lock_at"),
            "unlock_at": self._assignment_value(assignment, full_assignment, "unlock_at"),
            "peer_reviews": self._assignment_value(assignment, full_assignment, "peer_reviews", False),
            "automatic_peer_reviews": self._assignment_value(assignment, full_assignment, "automatic_peer_reviews", False),
            "peer_review_count": self._assignment_value(assignment, full_assignment, "peer_review_count"),
            "use_rubric_for_grading": self._assignment_value(assignment, full_assignment, "use_rubric_for_grading"),
            "rubric_settings": self._assignment_value(assignment, full_assignment, "rubric_settings"),
            "rubric": self._assignment_value(assignment, full_assignment, "rubric"),
            "group_category_id": self._assignment_value(assignment, full_assignment, "group_category_id"),
            "grade_group_students_individually": self._assignment_value(
                assignment,
                full_assignment,
                "grade_group_students_individually",
            ),
            "external_tool_tag_attributes": self._assignment_value(
                assignment,
                full_assignment,
                "external_tool_tag_attributes",
            ),
        }

    def get_calendar_sources(self):
        """
        Returns a list of dictionaries containing the Name and ID of favorite calendars.
        """
        # Start with the personal calendar
        sources = [{"name": "Personal Calendar", "id": f"user_{self.user.id}"}]
        
        # Get favorite courses (the ones on their dashboard/calendar tab)
        favorites = self.user.get_favorite_courses()
        
        for course in favorites:
            # Some favorites might be old or weird shells, 
            # but the 'Favorite' status is our best filter.
            name = getattr(course, 'name', f"Course {course.id}")
            sources.append({"name": name, "id": f"course_{course.id}"})
                
        return sources
    
    def get_course_weights(self, calendar_id):
        """
        Takes a calendar ID (e.g., 'course_12345') and returns a dictionary
        of assignment groups and their percentage weights.
        """
        # 1. Strip the 'course_' prefix to get the raw integer ID
        try:
            course_id = int(calendar_id.replace("course_", ""))
        except ValueError:
            return {"Error": "Invalid Course ID format"}

        try:
            course = self.canvas.get_course(course_id)
            
            # Check if the course actually uses weighted grading
            if not getattr(course, "apply_assignment_group_weights", False):
                return {"Grading Type": "Points-based (No weights applied)"}

            weights = {
                group["name"]: f"{group['weight_percent']}%"
                for group in self._get_assignment_group_lookup(course_id).values()
                if group["weight_percent"] is not None and group["weight_percent"] > 0
            }
            
            return weights if weights else {"Grading": "No weighted groups found"}
            
        except Exception as e:
            return {"Error": f"Could not retrieve weights: {str(e)}"}

    def get_student_workload(self, start_date, end_date, calendar_ids=None):
        if not calendar_ids:
            calendar_ids = [f"user_{self.user.id}"]

        # Force the time to cover the full range of the days provided
        # Format: 2026-02-25T00:00:00Z
        iso_start = f"{start_date}T00:00:00Z"
        iso_end = f"{end_date}T23:59:59Z"

        workload = []
        for code in calendar_ids:
            try:
                items = self.canvas.get_calendar_events(
                    type='assignment',
                    start_date=iso_start,
                    end_date=iso_end,
                    context_codes=[code],
                    all_events=True
                )
                
                for a in items:
                    try:
                        workload.append(self._assignment_payload(a, code))
                    except Exception:
                        continue
            except Exception:
                continue
                
        return workload
        # """
        # Retrieves assignments from specific calendars. 
        # If calendar_ids is None, it defaults to the user's personal calendar.
        # """
        # if not calendar_ids:
        #     calendar_ids = [f"user_{self.user.id}"]

        # # We must use type='assignment' to get actual graded items
        # assignments = self.canvas.get_calendar_events(
        #     type='assignment',
        #     start_date=start_date,
        #     end_date=end_date,
        #     context_codes=calendar_ids,
        #     all_events=True
        # )
        
        # return [{
        #     "title": getattr(a, 'title', 'Untitled'),
        #     "due_at": getattr(a, 'start_at', None),
        #     "points": getattr(a, 'assignment', {}).get('points_possible', 0),
        #     "context": getattr(a, 'context_name', 'Unknown Course')
        # } for a in assignments]

    def get_existing_events(self, start_date, end_date, calendar_ids=None):
        if not calendar_ids:
            calendar_ids = [f"user_{self.user.id}"]

        # Force the time to cover the full range of the days provided
        # Format: 2026-02-25T00:00:00Z
        iso_start = f"{start_date}T00:00:00Z"
        iso_end = f"{end_date}T23:59:59Z"

        all_events = []

        for code in calendar_ids:
            try:
                events = self.canvas.get_calendar_events(
                    type='event',
                    start_date=iso_start,
                    end_date=iso_end,
                    context_codes=[code],
                    all_events=True
                )
                for e in events:
                    event_id = getattr(e, 'id', None)
                    all_events.append({
                        "id": f"event_{event_id or code}_{getattr(e, 'start_at', '')}",
                        "include": True,
                        "canvas_event_id": event_id,
                        "context_code": code,
                        "title": getattr(e, 'title', 'Untitled'),
                        "start": getattr(e, 'start_at', None),
                        "end": getattr(e, 'end_at', None),
                        "context": getattr(e, 'context_name', 'Personal')
                    })
            except Exception as e:
                print(f"Skipping calendar {code} due to error: {e}")
                continue
                
        return all_events
        # if not calendar_ids:
        #     calendar_ids = [f"user_{self.user.id}"]

        # events = self.canvas.get_calendar_events(
        #     type='event',
        #     start_date=start_date,
        #     end_date=end_date,
        #     context_codes=calendar_ids,
        #     all_events=True
        # )
        
        # return [{
        #     "title": e.title,
        #     "start": e.start_at,
        #     "end": e.end_at,
        #     "context": getattr(e, 'context_name', 'Personal')
        # } for e in events]

    def get_combined_schedule(self, start_date, end_date):
        """
        Retrieves both assignments and events within a specific range.
        start_date/end_date should be strings in YYYY-MM-DD format.
        """
        context_code = f"user_{self.user.id}"

        # # 'type' can be 'event' or 'assignment'
        # # 'undated=False' ensures we only get things with a specific time slot
        # items = self.canvas.get_calendar_events(
        #     all_events=True,
        #     type='event', # You can call this twice, once for 'event' and once for 'assignment'
        #     start_date=start_date,
        #     end_date=end_date,
        #     context_codes=[context_code]
        # )
        # return items

        # The planner belongs to the main canvas object, not self.user
        # Dates must be in ISO format: YYYY-MM-DDTHH:MM:SSZ
        # For simplicity, we just add the time suffix to your date strings
        start = f"{start_date}T00:00:00Z"
        end = f"{end_date}T23:59:59Z"

        items = self.canvas.get_planner_items(start_date=start, end_date=end)
        
        workload = []
        for item in items:
            # Planner items have different attribute names than Calendar events
            # Use .get() or getattr() to avoid crashes if a field is missing
            workload.append({
                "title": getattr(item, 'plannable_title', "Untitled"),
                "due_at": getattr(item, 'plannable_date', "No Date"),
                "course": getattr(item, 'context_name', "General"),
                "points": getattr(item, 'points_possible', 0)
            })
        return workload

    def push_study_block(self, title, start_time, end_time, calendar_id=None, description=None):
        """
        Creates a block. If no calendar_id is provided, it defaults to the user's personal calendar.
        """
        target_context = calendar_id if calendar_id else f"user_{self.user.id}"
        details = description or "Auto-generated study session"
        
        event_dict = {
            "context_code": target_context,
            "title": title,
            "start_at": start_time,
            "end_at": end_time,
            "description": f"{STUDY_BLOCK_DESCRIPTION_MARKER}\n{details}"
        }
        return self.canvas.create_calendar_event(calendar_event=event_dict)

    def delete_generated_study_blocks(self, start_date, end_date, calendar_id=None):
        """
        Deletes study blocks generated by this app in the selected calendar/date range.
        """
        target_context = calendar_id if calendar_id else f"user_{self.user.id}"
        iso_start = self._calendar_boundary(start_date)
        iso_end = self._calendar_boundary(end_date, end_of_day=True)

        deleted = []
        failed = []

        events = self.canvas.get_calendar_events(
            type='event',
            start_date=iso_start,
            end_date=iso_end,
            context_codes=[target_context],
            all_events=True
        )

        for event in events:
            if not self._is_generated_study_block(event):
                continue

            try:
                event.delete()
                deleted.append({
                    "id": getattr(event, "id", None),
                    "title": getattr(event, "title", "Untitled"),
                })
            except Exception as exc:
                failed.append({
                    "id": getattr(event, "id", None),
                    "title": getattr(event, "title", "Untitled"),
                    "error": str(exc),
                })

        return {
            "deleted": deleted,
            "failed": failed,
        }
    
